### ISSUE TITLE
sudo: ipwm: command not found

### ISSUE THREAD

**Issue by rduttshukla** [kitsunyan/ipwm#1]
I am having issues running **ipwm** as superuser on RHEL 8. It ends with the following error

`sudo: ipwm: command not found`

Tried chmod +x as superuser but with the same result.

**PC**: Lenovo V130-15IKB
**OS**: Red Hat Enterprise Linux 8
**Graphics**: Intel UHD 620

**Comment by kitsunyan** [comment]
That's because `/usr/local/bin` is not included into `secure_path` in `sudoers` on RHEL, so when you install `ipwm` into `/usr/local/bin` (default behavior), it's not available via `sudo ipwm`. You should specify the full path (`sudo /usr/local/bin/ipwm`), install into `/usr/bin` (changing `BINDIR` and `LIBDIR` environment, e.g. `sudo env BINDIR=/usr/bin LIBDIR=/usr/lib make install`, though it's better to package `ipwm` instead).

**Comment by rduttshukla** [comment]
Moved from RHEL from a while now so not able to retry, I understand what I needed to do though. Thank you for your help.
